/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}

import '@stencil/router';

import {
  ActiveRouter,
} from '@stencil/router';

declare global {

  namespace StencilComponents {
    interface AppHero {
      'linkUrl': string;
    }
  }

  interface HTMLAppHeroElement extends StencilComponents.AppHero, HTMLStencilElement {}

  var HTMLAppHeroElement: {
    prototype: HTMLAppHeroElement;
    new (): HTMLAppHeroElement;
  };
  interface HTMLElementTagNameMap {
    'app-hero': HTMLAppHeroElement;
  }
  interface ElementTagNameMap {
    'app-hero': HTMLAppHeroElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'app-hero': JSXElements.AppHeroAttributes;
    }
  }
  namespace JSXElements {
    export interface AppHeroAttributes extends HTMLAttributes {
      'linkUrl'?: string;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface AppAbout {

    }
  }

  interface HTMLAppAboutElement extends StencilComponents.AppAbout, HTMLStencilElement {}

  var HTMLAppAboutElement: {
    prototype: HTMLAppAboutElement;
    new (): HTMLAppAboutElement;
  };
  interface HTMLElementTagNameMap {
    'app-about': HTMLAppAboutElement;
  }
  interface ElementTagNameMap {
    'app-about': HTMLAppAboutElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'app-about': JSXElements.AppAboutAttributes;
    }
  }
  namespace JSXElements {
    export interface AppAboutAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface AppHome {

    }
  }

  interface HTMLAppHomeElement extends StencilComponents.AppHome, HTMLStencilElement {}

  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };
  interface HTMLElementTagNameMap {
    'app-home': HTMLAppHomeElement;
  }
  interface ElementTagNameMap {
    'app-home': HTMLAppHomeElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'app-home': JSXElements.AppHomeAttributes;
    }
  }
  namespace JSXElements {
    export interface AppHomeAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface AppOpportunities {

    }
  }

  interface HTMLAppOpportunitiesElement extends StencilComponents.AppOpportunities, HTMLStencilElement {}

  var HTMLAppOpportunitiesElement: {
    prototype: HTMLAppOpportunitiesElement;
    new (): HTMLAppOpportunitiesElement;
  };
  interface HTMLElementTagNameMap {
    'app-opportunities': HTMLAppOpportunitiesElement;
  }
  interface ElementTagNameMap {
    'app-opportunities': HTMLAppOpportunitiesElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'app-opportunities': JSXElements.AppOpportunitiesAttributes;
    }
  }
  namespace JSXElements {
    export interface AppOpportunitiesAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface MyComponent {
      'activeRouter': ActiveRouter;
    }
  }

  interface HTMLMyComponentElement extends StencilComponents.MyComponent, HTMLStencilElement {}

  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };
  interface HTMLElementTagNameMap {
    'my-component': HTMLMyComponentElement;
  }
  interface ElementTagNameMap {
    'my-component': HTMLMyComponentElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'my-component': JSXElements.MyComponentAttributes;
    }
  }
  namespace JSXElements {
    export interface MyComponentAttributes extends HTMLAttributes {
      'activeRouter'?: ActiveRouter;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }

export declare function defineCustomElements(window: any): void;